//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ProjectId&quot;:&quot;eshop-puddle&quot;,&quot;TopicId&quot;:&quot;local-mooney-test&quot;,&quot;ElementCountThreshold&quot;:1000,&quot;RequestByteThreshold&quot;:5242880,&quot;DelayThreshold&quot;:3}.
        /// </summary>
        public static string ClientConfigSettings {
            get {
                return ResourceManager.GetString("ClientConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Type&quot;:&quot;service_account&quot;,&quot;project_id&quot;:&quot;eshop-puddle&quot;,&quot;private_key_id&quot;:&quot;acd4411bb8ffdafe22babf84d49928821f9a17d6&quot;,&quot;private_key&quot;:&quot;-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDqPNSI1Ww8+w0\nJrDXawuDYLxJnlWPMgZlRFbVfyTuiDFc8iJZWAIC8CkHnPJR0ocYMF629IP5uwea\n0JequSJS6dX0g7zeX0VhQQagYYmIn8ou8N1Pk0D/sFS9z+n/1/wDIqgCm4xx20Ks\neoWEODiu+7eoQUTWZFMUb/ri7q4uzbcrHX7HnPXGdMvBqJogvir3QNiiJfiZ42Ba\ngKWz4CFz5m3JJJYBAwbKNK1htvxiLFLSxttw7DuTq6Uu5NpGB8JInWQTtqOlk/ZM\n5YpmQIPD1uCKpy6DbE2BCjHi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CloudServiceCredentials {
            get {
                return ResourceManager.GetString("CloudServiceCredentials", resourceCulture);
            }
        }
    }
}
